github:
  repos:
    - 
        org: <organization>
        repo: <repository>
        reviewers:
          - # Level 1
            - <reviewer_level1>
          - # Level 2
            - <reviewer_level2>
  pull_request_title_tag:
    format: '[{}]'
    pattern: '\[(\w+)\]'
testing_mode: false
debug_mode: false
maintainers: # Used for recieve emails about failures
  - <maintainer_email>
events_proxy:
  use: true
  check_timeout_seconds: 60
