github:
  repos:
    - 
        org: <organization>
        repo: <repository>
        reviewers:
          - # Level 1
            - <reviewer_level1>
          - # Level 2
            - <reviewer_level2>
  pull_request_title_tag:
    format: '[{}]'
    pattern: '\[(\w+)\]'
testing_mode: false
debug_mode: false
maintainers: # Used for recieve emails about failures
  - <maintainer_email>
events_handler:
  use_github_events_proxy: true
  check_timeout_seconds: 60
reports:
  daily: '9:00'  # send the report every day at this time
  receivers:
    - <email>
