github:
  repos: [
    'organization/repository'
  ]
  login:
    client_id: <client_id>
    client_secret: <client_secret>
  title_status_pattern: '\[(\w+)\]'
  pr_inactivity_timeout:
    days: 2
    hours: 0
email_addr: <the_bot_email_address>

